project:
  type: website
  resources: 
    - images/*

website:
  title: "ML+X Community Shared Resources"
  page-navigation: true
  
  sidebar:
    tools:
      - icon: github
        href: https://github.com/UW-Madison-DataScience/ML-X-Community
        text: "GitHub organization"
    background: "#dbd9d9"
    logo: "/images/ML+X_Logo_Secondary_Transparent.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: Guides/index.qmd
        text: "Guides"
      - href: EDA-examples/index.qmd
        text: "EDA examples"
      - href: foundational-models.qmd
        text: "Foundational models"
      - href: external-guides.qmd
        text: "External guides"
      - href: glossary.qmd
        text: "Glossary of ML terms"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    # css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

